[tool.poetry]
name = "opendataplatform"
version = "0.1.0"
description = ""
authors = ["David Mungai <mungahdaudi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.2"
django-types = "^0.19.1"
django-stubs-ext = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
